# -*- coding: utf-8 -*-
"""IS211_Assignment3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rpYXXm2TYITnuy0Pa8JYcgyFZnGUFSZe
"""

import argparse
import urllib.request
import logging
import datetime


def downloadData(url):
  with urllib.request.urlopen(url) as response:
    data = response.read().decode('utf-8')
    return data

def dataLine(url):
    data = downloadData(url)
    data_line= data.split("\r\n")
    return data_line

def processData(url):
    data_line= dataLine(url)
    data_line5 = data_line[:5]
    data_line0 = data_line5[0].split(",")
    return data_line0

def pathData(url):
    date_line0= processData(url)
    path= date_line0[0]
    return path

def dataTimeData(url):
    date_line0= processData(url)
    data_time= date_line0[1]
    return data_time

def browserData(url):
    date_line0= processData(url)  
    browser= date_line0[2]
    return browser

def statusOfRequestData(url):
    date_line0= processData(url)  
    status_of_request = date_line0[3] 
    return status_of_request

def requestSizeInBytesData(url):
    date_line0= processData(url)  
    request_size_in_bytes =date_line0[4]
    return request_size_in_bytes 

def imageCounter(url):
    date_line0= processData(url)  
    data_line = dataLine(url)
    image_counter = {}
    for line in data_line:
        item = line.split(",")
        path =item[0]
        extension= path.rpartition(".")[-1]
        if extension in image_counter:
          image_counter[extension] +=1
        else:
          image_counter[extension] =1
    return image_counter

def browserCounter(url):
    data_line = dataLine(url)
    browser_counter = {}
    for line in data_line:
        if line =='':continue
        item = line.split(",")
        browser =item[2]
        if browser in browser_counter:
          browser_counter[browser] +=1
        else:
          browser_counter[browser] =1
    return browser_counter


def main(url):
    print(f"Running main with URL = {url}...")
    print (dataLine(url))
    print(processData(url))
    print(pathData(url))
    print(dataTimeData(url))
    print(browserData(url))
    print(statusOfRequestData(url))
    print(requestSizeInBytesData(url))
    print(imageCounter(url))
    print(browserCounter(url))
  
if __name__ == "__main__":
    """Main entry point"""
    parser = argparse.ArgumentParser()
    parser.add_argument("--url", help="URL to the datafile", type=str, required=True)
    args = parser.parse_args()
    main(args.url)
#main("http://s3.amazonaws.com/cuny-is211-spring2015/weblog.csv")